# Generated by Django 3.2.5 on 2021-08-03 19:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('adoption_date', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_group', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('life_span', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
            ],
            managers=[
                ('dogs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TempDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_group', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('life_span', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
            ],
            managers=[
                ('dogs', django.db.models.manager.Manager()),
            ],
        ),
    ]
